### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by eseuteo** [Shiawasemono/Scouts-Tarea-2#22]
- scout @MrYompi 
  - [x] foros - banner duplicado
  - [x] historial - peta la query

- scouter @PabloCorralFranco 
  - [x] enlaces banner
  - [x] perfil ponerlo como en scout
  - [x] quitar pestaña documentos

- coordinador
  - [x] cambiar banner en foros, historial, eventos y perfil con un when para que el banner cambie si eres coordinador @MrYompi 
  - [x] quitar enlace documentación del banner @MrYompi 
  - [x] enlace eventos @eseuteo
  - [x ] perfil peta @eseuteo
